# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hocsau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hasChild',
            field=models.BooleanField(default=False),
        ),
    ]
